import{a as b,S as v,i as l}from"./assets/vendor-iiPpPmup.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))i(r);new MutationObserver(r=>{for(const s of r)if(s.type==="childList")for(const a of s.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&i(a)}).observe(document,{childList:!0,subtree:!0});function n(r){const s={};return r.integrity&&(s.integrity=r.integrity),r.referrerPolicy&&(s.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?s.credentials="include":r.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function i(r){if(r.ep)return;r.ep=!0;const s=n(r);fetch(r.href,s)}})();const B="https://pixabay.com/api/";function $(){return"54365161-150e0cc42a1017ee523dff469"}async function A(t,e=1){const n=$();if(!String(n).trim())throw new Error("MISSING_API_KEY");const i={key:n.trim(),q:String(t).trim(),image_type:"photo",orientation:"horizontal",safesearch:!0,page:Number(e)||1,per_page:15};return(await b.get(B,{params:i})).data}const o=document.querySelector(".gallery"),c=document.querySelector(".loader-wrap"),u=document.querySelector(".btn-load-more");let y=null;function R(t){const{webformatURL:e,largeImageURL:n,tags:i="",likes:r=0,views:s=0,comments:a=0,downloads:M=0}=t,L=String(i).slice(0,200).replace(/"/g,"&quot;").replace(/'/g,"&#39;").replace(/</g,"&lt;").replace(/>/g,"&gt;");return`
<li class="gallery-item">
  <a class="gallery-item__link" href="${n}" title="${L}">
    <img
      class="gallery-item__img"
      src="${e}"
      alt="${L}"
      loading="lazy"
      width="640"
      height="360"
    />
    <div class="gallery-item__info">
      <span class="gallery-item__info-item">❤️ ${r}</span>
      <span class="gallery-item__info-item">👁 ${s}</span>
      <span class="gallery-item__info-item">💬 ${a}</span>
      <span class="gallery-item__info-item">⬇ ${M}</span>
    </div>
  </a>
</li>`}function I(t,e=!1){if(!o)return;if(!Array.isArray(t)||t.length===0){e||(o.innerHTML="");return}const n=t.map(R).join("");e?o.insertAdjacentHTML("beforeend",n):o.innerHTML=n,y?y.refresh():y=new v(".gallery a",{captionsData:"title",captionDelay:250})}function T(){o&&(o.innerHTML="")}function w(){c&&c.classList.remove("is-hidden")}function d(){c&&c.classList.add("is-hidden")}function x(){u&&u.classList.remove("is-hidden")}function f(){u&&u.classList.add("is-hidden")}const k=15,h=document.querySelector(".form"),E=document.querySelector(".btn-load-more"),S=document.querySelector(".gallery"),g=document.querySelector(".end-message");let p="",m=1;function O(){g&&g.classList.add("is-hidden")}function _(){g&&g.classList.remove("is-hidden")}function P(t){return m*k>=t}function q(t){let e="Something went wrong. Please try again.";return t.message==="MISSING_API_KEY"?e="Pixabay API key is missing. Create .env and add VITE_PIXABAY_API_KEY=your_key (get key: https://pixabay.com/api/docs/)":t.response?.status===429?e="Too many requests. Please try again later.":t.response?.status===400?e="Invalid request (e.g. missing API key). Check .env and VITE_PIXABAY_API_KEY.":t.message&&(e=t.message),e}function H(){if(!S)return;const t=S.querySelector(".gallery-item");if(!t)return;const{height:e}=t.getBoundingClientRect();window.scrollBy({top:2*e,behavior:"smooth"})}async function K(t){t.preventDefault();const e=h?.querySelector('input[name="search-text"]'),n=e?e.value.trim():"";if(n){p=n,m=1,f(),O(),w(),T();try{const i=await A(n,1);if(d(),!i||!Array.isArray(i.hits)){l.info({title:"Info",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",timeout:4e3});return}if(i.hits.length===0){l.info({title:"Info",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",timeout:4e3});return}I(i.hits),P(i.totalHits)?(f(),_()):x()}catch(i){d(),l.error({title:"Error",message:q(i),position:"topRight",timeout:6e3})}}}async function N(){if(!p)return;const t=m+1;w();try{const e=await A(p,t);if(d(),!e||!Array.isArray(e.hits)||e.hits.length===0){f(),_();return}m=t,I(e.hits,!0),P(e.totalHits)&&(f(),_()),H()}catch(e){d(),l.error({title:"Error",message:q(e),position:"topRight",timeout:6e3})}}h&&h.addEventListener("submit",K);E&&E.addEventListener("click",N);
//# sourceMappingURL=index.js.map
